/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bendikjohansen' at '3/23/17 1:33 PM' with Gradle 2.14.1
 *
 * @author bendikjohansen, @date 3/23/17 1:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
